### ISSUE TITLE
Paper code

### ISSUE THREAD

**Issue by liuyue718** [zengxianyu/jsws#1]
Hello, I am a graduate student, now I want to reproduce your paper, what I downloaded is the version you uploaded before, I see you deleted all the previous ones, is there any mistake?Looking forward to your reply. I think it is very important to me，thanks

**Comment by zengxianyu** [comment]
the new one is structured simpler and tricks are removed but the
performance is almost the same as the old one. The old one is still on the
github and its name was ''jsws-old' now

liuyue718 <notifications@github.com> 于2020年5月12日周二 下午4:19写道：

**Comment by zengxianyu** [comment]
Last year my computer was broken and the model parameter files for the old
ones were lost. So I am reproducing that project and the model files will
be available soon. There is no mistake in that old one and you can still
use it for training or wait for me providing parameter files for the new one

Yu Zeng <zengxianyu18@gmail.com> 于2020年5月15日周五 下午2:10写道：
