### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by SharhadBashar** [zengxianyu/jsws#4]
youre missing the file val.txt for 
`voc_val_split = '/home/zeng/data/datasets/segmentation/VOCdevkit/VOC2012/ImageSets/Segmentation/val.txt'`
as well as this one:
`sal_val_img_dir = '/home/zeng/data/datasets/saliency/ECSSD/images'`

**Comment by zengxianyu** [comment]
val.txt is a part of VOC2012 dataset and I provided download link to it.

I have added the download link to ECSSD
